import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { loadBoard } from "../src/board-files";
import {
  createSourceSpecMigrationPlan,
  formatSourceSpecMigrationPlan,
  readSourceSpecCandidateFiles
} from "../src/source-spec-migration";

describe("source spec migration planning", () => {
  it("classifies specs, docs, generated output, archives, and unknown Markdown", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "duneboard-migration-"));

    try {
      await writeProjectFile(root, "tasks/DB-0001-root.md", task("DB-0001"));
      await writeProjectFile(root, "tasks/DB-0002-feature.md", task("DB-0002"));
      await writeProjectFile(root, "docs/specs/active-db-0002.md", "# Active feature spec\n\nOwner: DB-0002\n");
      await writeProjectFile(root, "task/design/stale-db-0001.md", "# Stale implementation spec\n\nFold into DB-0001.\n");
      await writeProjectFile(root, "docs/generated/api.md", "# API\n\nGenerated by tooling. Do not edit.\n");
      await writeProjectFile(root, "docs/architecture.md", "# Architecture\n\nProject-level architecture.\n");
      await writeProjectFile(root, "notes/mystery.md", "# Mystery\n\nNeeds human review.\n");
      await writeProjectFile(root, "tasks/archive/DB-0002-old.md", task("DB-0002"));

      const board = await loadBoard(root);
      const files = await readSourceSpecCandidateFiles(board.root, board.taskDirs);
      const plan = createSourceSpecMigrationPlan({
        files,
        root: board.root,
        taskDirs: board.taskDirs,
        tasks: board.index.tasks
      });

      expect(plan.summary).toEqual({
        generated_documentation: 1,
        non_task_documentation: 1,
        task_archive: 1,
        task_related_spec: 2,
        unknown: 1
      });
      expect(plan.items).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            archivePath: "tasks/archive/docs/specs/active-db-0002.md",
            classification: "task_related_spec",
            ownerTaskId: "DB-0002",
            provenanceNote: "Migrated source spec docs/specs/active-db-0002.md to tasks/archive/docs/specs/active-db-0002.md.",
            sourcePath: "docs/specs/active-db-0002.md"
          }),
          expect.objectContaining({
            archivePath: "tasks/archive/task/design/stale-db-0001.md",
            classification: "task_related_spec",
            ownerTaskId: "DB-0001",
            sourcePath: "task/design/stale-db-0001.md"
          }),
          expect.objectContaining({
            classification: "generated_documentation",
            sourcePath: "docs/generated/api.md"
          }),
          expect.objectContaining({
            classification: "non_task_documentation",
            sourcePath: "docs/architecture.md"
          }),
          expect.objectContaining({
            classification: "task_archive",
            sourcePath: "tasks/archive/DB-0002-old.md"
          }),
          expect.objectContaining({
            classification: "unknown",
            sourcePath: "notes/mystery.md"
          })
        ])
      );

      expect(formatSourceSpecMigrationPlan(plan)).toContain("Fold current design facts into DB-0002 ## Design.");
    } finally {
      await rm(root, { force: true, recursive: true });
    }
  });
});

async function writeProjectFile(root: string, relativePath: string, content: string): Promise<void> {
  const absolutePath = path.join(root, relativePath);
  await mkdir(path.dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, content);
}

function task(id: string): string {
  return `---
id: ${id}
title: Task ${id}
kind: task
status: ready
priority: P1
parent: null
depends_on: []
blocked_by: []
relates_to: []
assignee: null
labels: [test]
---

## Goal

Test task.

## Design

Current task design.

## Acceptance Criteria

- [ ] Works
`;
}
